# Generated by Django 2.0.1 on 2018-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scu', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('sem', models.DecimalField(decimal_places=0, max_digits=1)),
                ('bday', models.DateField()),
                ('gender', models.BooleanField()),
                ('testGiven', models.BooleanField()),
            ],
        ),
    ]
