# Generated by Django 2.0.1 on 2018-04-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0002_studenttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
