# Generated by Django 2.0.1 on 2018-04-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0003_studenttable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='EI',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='JP',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='SN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='TF',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
