# Generated by Django 2.0.1 on 2018-04-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0004_auto_20180417_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='EI',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='JP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='SN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='TF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
