# Generated by Django 2.0.1 on 2018-04-18 03:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0005_auto_20180418_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='json',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
