# Generated by Django 2.0.1 on 2018-04-18 06:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0006_studenttable_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='json',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
