# Generated by Django 2.0.1 on 2018-04-18 06:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0007_auto_20180418_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='json',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
